#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/zmt/Documents/ohos/flutter/flutter_flutter"
export "FLUTTER_APPLICATION_PATH=/Users/zmt/Documents/ohos/github/extended_text/example"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_ENGINE=/Users/zmt/Documents/ohos/flutter/engine/src"
export "LOCAL_ENGINE=ohos_debug_unopt_arm64"
export "ARCHS=arm64"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.dart_tool/package_config.json"
