// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://BackgroundTextDemo',
  'fluttercandies://CustomTextOverflowDemo',
  'fluttercandies://MiddleTextOverflowDemo',
  'fluttercandies://TextDemo',
  'fluttercandies://TextSelectionDemo',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'workaround for issue 24335/24337 about background'
  ///
  /// [name] : 'fluttercandies://BackgroundTextDemo'
  ///
  /// [routeName] : 'BackgroundText'
  ///
  /// [description] : 'workaround for issue 24335/24337 about background'
  static const String fluttercandiesBackgroundTextDemo =
      'fluttercandies://BackgroundTextDemo';

  /// 'workaround for issue 26748. how to custom text overflow'
  ///
  /// [name] : 'fluttercandies://CustomTextOverflowDemo'
  ///
  /// [routeName] : 'CustomTextOverflow'
  ///
  /// [description] : 'workaround for issue 26748. how to custom text overflow'
  static const String fluttercandiesCustomTextOverflowDemo =
      'fluttercandies://CustomTextOverflowDemo';

  /// 'how to make text overflow in middle.'
  ///
  /// [name] : 'fluttercandies://MiddleTextOverflowDemo'
  ///
  /// [routeName] : 'MiddleTextOverflow'
  ///
  /// [description] : 'how to make text overflow in middle.'
  static const String fluttercandiesMiddleTextOverflowDemo =
      'fluttercandies://MiddleTextOverflowDemo';

  /// 'quickly build special text'
  ///
  /// [name] : 'fluttercandies://TextDemo'
  ///
  /// [routeName] : 'Text'
  ///
  /// [description] : 'quickly build special text'
  static const String fluttercandiesTextDemo = 'fluttercandies://TextDemo';

  /// 'text selection support'
  ///
  /// [name] : 'fluttercandies://TextSelectionDemo'
  ///
  /// [routeName] : 'TextSelection'
  ///
  /// [description] : 'text selection support'
  static const String fluttercandiesTextSelectionDemo =
      'fluttercandies://TextSelectionDemo';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
