// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.9
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://BackgroundTextDemo',
  'fluttercandies://CustomTextOverflowDemo',
  'fluttercandies://JoinZeroWidthSpace',
  'fluttercandies://RegExpTextDemo',
  'fluttercandies://SelectionAreaDemo',
  'fluttercandies://TextDemo',
  'fluttercandies://mainpage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'workaround for issue 24335/24337 about background'
  ///
  /// [name] : 'fluttercandies://BackgroundTextDemo'
  ///
  /// [routeName] : 'BackgroundText'
  ///
  /// [description] : 'workaround for issue 24335/24337 about background'
  static const String fluttercandiesBackgroundTextDemo =
      'fluttercandies://BackgroundTextDemo';

  /// 'workaround for issue 26748. how to custom text overflow'
  ///
  /// [name] : 'fluttercandies://CustomTextOverflowDemo'
  ///
  /// [routeName] : 'CustomTextOverflow'
  ///
  /// [description] : 'workaround for issue 26748. how to custom text overflow'
  static const String fluttercandiesCustomTextOverflowDemo =
      'fluttercandies://CustomTextOverflowDemo';

  /// 'make line breaking and overflow style better, workaround for issue 18761.'
  ///
  /// [name] : 'fluttercandies://JoinZeroWidthSpace'
  ///
  /// [routeName] : 'JoinZeroWidthSpace'
  ///
  /// [description] : 'make line breaking and overflow style better, workaround for issue 18761.'
  static const String fluttercandiesJoinZeroWidthSpace =
      'fluttercandies://JoinZeroWidthSpace';

  /// 'quickly build special text with RegExp'
  ///
  /// [name] : 'fluttercandies://RegExpTextDemo'
  ///
  /// [routeName] : 'RegExText'
  ///
  /// [description] : 'quickly build special text with RegExp'
  static const String fluttercandiesRegExpTextDemo =
      'fluttercandies://RegExpTextDemo';

  /// 'SelectionArea support'
  ///
  /// [name] : 'fluttercandies://SelectionAreaDemo'
  ///
  /// [routeName] : 'SelectionArea'
  ///
  /// [description] : 'SelectionArea support'
  static const String fluttercandiesSelectionAreaDemo =
      'fluttercandies://SelectionAreaDemo';

  /// 'quickly build special text'
  ///
  /// [name] : 'fluttercandies://TextDemo'
  ///
  /// [routeName] : 'Text'
  ///
  /// [description] : 'quickly build special text'
  static const String fluttercandiesTextDemo = 'fluttercandies://TextDemo';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
